server:
  port: 8083

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

destination:
  service:
    url: http://localhost:8081/queue/publish

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000